import { CoinIcons } from './CoinIcons';

export type CoinDefinition = {
  id: string;
  icon: string;
  name: string;
  symbol: string;
  networks: string[];
  referral: string;
};

export const AllCoins: CoinDefinition[] = [
  {
    id: '0x',
    icon: CoinIcons.Zrx,
    name: '0x',
    symbol: 'ZRX',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: '1inch',
    icon: CoinIcons.OneInch,
    name: '1Inch',
    symbol: '1INCH',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'aave',
    icon: CoinIcons.Aave,
    name: 'Aave',
    symbol: 'AAVE',
    networks: ['BSC', 'ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'algorand',
    icon: CoinIcons.Algo,
    name: 'Algorand',
    symbol: 'ALGO',
    networks: ['ALGO'],
    referral: 'FractalMedia',
  },
  {
    id: 'augur',
    icon: CoinIcons.Rep,
    name: 'Augur',
    symbol: 'REP',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'band-protocol',
    icon: CoinIcons.Band,
    name: 'Band Protocol',
    symbol: 'BAND',
    networks: ['BAND'],
    referral: 'FractalMedia',
  },
  {
    id: 'basic-attention-token',
    icon: CoinIcons.Bat,
    name: 'Basic Attention Token',
    symbol: 'BAT',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'binancecoin',
    icon: CoinIcons.Bnb,
    name: 'Binance Coin',
    symbol: 'BNB',
    networks: ['BNB', 'BSC'],
    referral: 'FractalMedia',
  },
  {
    id: 'bitcoin',
    icon: CoinIcons.Btc,
    name: 'Bitcoin',
    symbol: 'BTC',
    networks: ['BTC'],
    referral: 'FractalMedia',
  },
  {
    id: 'bitcoin-cash',
    icon: CoinIcons.Bch,
    name: 'Bitcoin Cash',
    symbol: 'BCH',
    networks: ['BCH'],
    referral: 'FractalMedia',
  },
  {
    id: 'bitcoin-gold',
    icon: CoinIcons.Btg,
    name: 'Bitcoin God',
    symbol: 'BTG',
    networks: ['BTG'],
    referral: 'FractalMedia',
  },
  {
    id: 'bittorrent-2',
    icon: CoinIcons.Btt,
    name: 'BitTorrent',
    symbol: 'BTT',
    networks: ['TRX'],
    referral: 'FractalMedia',
  },
  {
    id: 'cardano',
    icon: CoinIcons.Ada,
    name: 'Cardano',
    symbol: 'ADA',
    networks: ['ADA'],
    referral: 'FractalMedia',
  },
  {
    id: 'chainlink',
    icon: CoinIcons.Link,
    name: 'ChainLink',
    symbol: 'LINK',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'chiliz',
    icon: CoinIcons.Chz,
    name: 'Chiliz',
    symbol: 'CHZ',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'cosmos',
    icon: CoinIcons.Atom,
    name: 'Cosmos',
    symbol: 'ATOM',
    networks: ['ATOM'],
    referral: 'FractalMedia',
  },
  {
    id: 'crypto-com-chain',
    icon: CoinIcons.Cro,
    name: 'Crypto.com Coin',
    symbol: 'CRO',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'dash',
    icon: CoinIcons.Dash,
    name: 'Dash',
    symbol: 'DASH',
    networks: ['DASH'],
    referral: 'FractalMedia',
  },
  {
    id: 'decentraland',
    icon: CoinIcons.Mana,
    name: 'Decentraland',
    symbol: 'MANA',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'digibyte',
    icon: CoinIcons.Dgb,
    name: 'DigiByte',
    symbol: 'DGB',
    networks: ['DGB'],
    referral: 'FractalMedia',
  },
  {
    id: 'dogecoin',
    icon: CoinIcons.Doge,
    name: 'Dogecoin',
    symbol: 'DOGE',
    networks: ['DOGE'],
    referral: 'FractalMedia',
  },
  {
    id: 'dogelon-mars',
    icon: CoinIcons.Elon,
    name: 'Dogelon Mars',
    symbol: 'ELON',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'enjincoin',
    icon: CoinIcons.Enj,
    name: 'Enjin Coin',
    symbol: 'ENJ',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'eos',
    icon: CoinIcons.Eos,
    name: 'EOS',
    symbol: 'EOS',
    networks: ['EOS'],
    referral: 'FractalMedia',
  },
  {
    id: 'ethereum',
    icon: CoinIcons.Eth,
    name: 'Ethereum',
    symbol: 'ETH',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'ethereum-classic',
    icon: CoinIcons.Etc,
    name: 'Ethereum Classic',
    symbol: 'ETC',
    networks: ['ETC'],
    referral: 'FractalMedia',
  },
  {
    id: 'funfair',
    icon: CoinIcons.Fun,
    name: 'FUNToken',
    symbol: 'FUN',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'gas',
    icon: CoinIcons.Gas,
    name: 'Gas',
    symbol: 'GAS',
    networks: ['NEO'],
    referral: 'FractalMedia',
  },
  {
    id: 'holotoken',
    icon: CoinIcons.Hot,
    name: 'Holo',
    symbol: 'HOT',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'icon',
    icon: CoinIcons.Icx,
    name: 'Icon',
    symbol: 'ICX',
    networks: ['ICX'],
    referral: 'FractalMedia',
  },
  {
    id: 'klever',
    icon: CoinIcons.Klv,
    name: 'Klever',
    symbol: 'KLV',
    networks: ['TRX'],
    referral: 'FractalMedia',
  },
  {
    id: 'kyber-network-crystal',
    icon: CoinIcons.Knc,
    name: 'KyberNetwork',
    symbol: 'KNC',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'lisk',
    icon: CoinIcons.Lsk,
    name: 'Lisk',
    symbol: 'LSK',
    networks: ['LSK'],
    referral: 'FractalMedia',
  },
  {
    id: 'litecoin',
    icon: CoinIcons.Ltc,
    name: 'Litecoin',
    symbol: 'LTC',
    networks: ['LTC'],
    referral: 'FractalMedia',
  },
  {
    id: 'matic-network',
    icon: CoinIcons.Matic,
    name: 'Matic (Polygon)',
    symbol: 'MATIC',
    networks: ['BSC', 'ETH', 'MATIC'],
    referral: 'FractalMedia',
  },
  {
    id: 'metal',
    icon: CoinIcons.Mtl,
    name: 'Metal',
    symbol: 'MTL',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'monero',
    icon: CoinIcons.Xmr,
    name: 'Monero',
    symbol: 'XMR',
    networks: ['XMR'],
    referral: 'FractalMedia',
  },
  {
    id: 'nano',
    icon: CoinIcons.Nano,
    name: 'Nano',
    symbol: 'NANO',
    networks: ['NANO'],
    referral: 'FractalMedia',
  },
  {
    id: 'neo',
    icon: CoinIcons.Neo,
    name: 'Neo',
    symbol: 'NEO',
    networks: ['NEO'],
    referral: 'FractalMedia',
  },
  {
    id: 'pancakeswap-token',
    icon: CoinIcons.Cake,
    name: 'PancakeSwap',
    symbol: 'CAKE',
    networks: ['BSC'],
    referral: 'i0kx-z4kc',
  },
  {
    id: 'qtum',
    icon: CoinIcons.Qtum,
    name: 'Qtum',
    symbol: 'QTUM',
    networks: ['QTUM'],
    referral: 'FractalMedia',
  },
  {
    id: 'ravencoin',
    icon: CoinIcons.Rvn,
    name: 'Ravencoin',
    symbol: 'RVN',
    networks: ['RVN'],
    referral: 'FractalMedia',
  },
  {
    id: 'reserve-rights-token',
    icon: CoinIcons.Rsr,
    name: 'Reserve Rights',
    symbol: 'RSR',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'ripple',
    icon: CoinIcons.Xrp,
    name: 'Ripple',
    symbol: 'XRP',
    networks: ['XRP'],
    referral: 'FractalMedia',
  },
  {
    id: 'safemoon',
    icon: CoinIcons.Safemoon,
    name: 'SafeMoon (V1)',
    symbol: 'SAFEMOON',
    networks: ['BSC', 'BSC-V2'],
    referral: 'FractalMedia',
  },
  {
    id: 'safemoon-2',
    icon: CoinIcons.Sfm,
    name: 'SafeMoon (V2)',
    symbol: 'SFM',
    networks: ['BSC'],
    referral: 'FractalMedia',
  },
  {
    id: 'saitama-inu',
    icon: CoinIcons.Saitama,
    name: 'Saitama Inu',
    symbol: 'SAITAMA',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'siacoin',
    icon: CoinIcons.Sc,
    name: 'Saicoin',
    symbol: 'SC',
    networks: ['SC'],
    referral: 'FractalMedia',
  },
  {
    id: 'shiba-inu',
    icon: CoinIcons.Shib,
    name: 'Shiba Inu',
    symbol: 'SHIB',
    networks: ['BSC', 'ETH', 'KCC'],
    referral: 'FractalMedia',
  },
  {
    id: 'solana',
    icon: CoinIcons.Sol,
    name: 'Solana',
    symbol: 'SOL',
    networks: ['BSC', 'SOL'],
    referral: 'FractalMedia',
  },
  {
    id: 'stellar',
    icon: CoinIcons.Xlm,
    name: 'Stellar Lumens',
    symbol: 'XLM',
    networks: ['XLM'],
    referral: 'FractalMedia',
  },
  {
    id: 'sushi',
    icon: CoinIcons.Sushi,
    name: 'Sushi',
    symbol: 'SUSHI',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'tezos',
    icon: CoinIcons.Xtz,
    name: 'Tezos',
    symbol: 'XTZ',
    networks: ['XTZ'],
    referral: 'FractalMedia',
  },
  {
    id: 'tron',
    icon: CoinIcons.Trx,
    name: 'Tron',
    symbol: 'TRX',
    networks: ['TRX'],
    referral: 'FractalMedia',
  },
  {
    id: 'uniswap',
    icon: CoinIcons.Uni,
    name: 'Uniswap',
    symbol: 'UNI',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'tether',
    icon: CoinIcons.Usdt,
    name: 'TetherUS',
    symbol: 'USDT',
    networks: ['BSC', 'ETH', 'TRX'],
    referral: 'FractalMedia',
  },
  {
    id: 'vechain',
    icon: CoinIcons.Vet,
    name: 'VeChain',
    symbol: 'VET',
    networks: ['VET'],
    referral: 'FractalMedia',
  },
  {
    id: 'waves',
    icon: CoinIcons.Waves,
    name: 'Waves',
    symbol: 'WAVES',
    networks: ['WAVES'],
    referral: 'FractalMedia',
  },
  {
    id: 'wink',
    icon: CoinIcons.Win,
    name: 'WINk',
    symbol: 'WIN',
    networks: ['TRX'],
    referral: 'FractalMedia',
  },
  {
    id: 'wrapped-bitcoin',
    icon: CoinIcons.Wbtc,
    name: 'Wrapped Bitcoin',
    symbol: 'WBTC',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'verge',
    icon: CoinIcons.Xvg,
    name: 'Verge',
    symbol: 'XVG',
    networks: ['XVG'],
    referral: 'FractalMedia',
  },
  {
    id: 'yearn-finance',
    icon: CoinIcons.Yfi,
    name: 'Yearn.finance',
    symbol: 'YFI',
    networks: ['ETH'],
    referral: 'FractalMedia',
  },
  {
    id: 'zcash',
    icon: CoinIcons.Zec,
    name: 'Zcash',
    symbol: 'ZEC',
    networks: ['ZEC'],
    referral: 'FractalMedia',
  },
  {
    id: 'zilliqa',
    icon: CoinIcons.Zil,
    name: 'Zilliqa',
    symbol: 'ZIL',
    networks: ['ZIL'],
    referral: 'FractalMedia',
  },
];
