import { CoinIcons } from './CoinIcons';

export type CoinDefinition = {
  id: string;
  icon: string;
  name: string;
  symbol: string;
  blockchains: string[];
  referrals: string[];
};

export const ALL_COINS: CoinDefinition[] = [
  {
    id: '0x',
    icon: CoinIcons.Zrx,
    name: '0x',
    symbol: 'ZRX',
    blockchains: ['ETH'],
    referrals: ['i9p3-ao71'],
  },
  {
    id: '1inch',
    icon: CoinIcons.OneInch,
    name: '1Inch',
    symbol: '1INCH',
    blockchains: ['ETH'],
    referrals: ['jpww-daqu'],
  },
  {
    id: 'aave',
    icon: CoinIcons.Aave,
    name: 'Aave',
    symbol: 'AAVE',
    blockchains: ['BSC', 'ETH'],
    referrals: ['2xc8-cp4e'],
  },
  {
    id: 'algorand',
    icon: CoinIcons.Algo,
    name: 'Algorand',
    symbol: 'ALGO',
    blockchains: ['ETH', 'BSC'],
    referrals: ['4rcp-6phh'],
  },
  {
    id: 'augur',
    icon: CoinIcons.Rep,
    name: 'Augur',
    symbol: 'REP',
    blockchains: ['ETH'],
    referrals: ['futc-3x8d'],
  },
  {
    id: 'baby-doge-coin',
    icon: CoinIcons.BabyDoge,
    name: 'Baby Doge',
    symbol: 'BABYDOGE',
    blockchains: ['BSC'],
    referrals: ['iwtu-dkg4'],
  },
  {
    id: 'band-protocol',
    icon: CoinIcons.Band,
    name: 'Band Protocol',
    symbol: 'BAND',
    blockchains: ['BAND'],
    referrals: ['6yis-m6qd'],
  },
  {
    id: 'basic-attention-token',
    icon: CoinIcons.Bat,
    name: 'Basic Attention Token',
    symbol: 'BAT',
    blockchains: ['ETH'],
    referrals: ['9qny-5sqm'],
  },
  {
    id: 'binancecoin',
    icon: CoinIcons.Bnb,
    name: 'Binance Coin',
    symbol: 'BNB',
    blockchains: ['BNB', 'BSC'],
    referrals: ['ba8w-ywck'],
  },
  {
    id: 'bitcoin',
    icon: CoinIcons.Btc,
    name: 'Bitcoin',
    symbol: 'BTC',
    blockchains: ['BTC'],
    referrals: ['jsbv-p7ge'],
  },
  {
    id: 'bitcoin-cash',
    icon: CoinIcons.Bch,
    name: 'Bitcoin Cash',
    symbol: 'BCH',
    blockchains: ['BCH'],
    referrals: ['3x9l-lsss'],
  },
  {
    id: 'bitcoin-gold',
    icon: CoinIcons.Btg,
    name: 'Bitcoin God',
    symbol: 'BTG',
    blockchains: ['BTG'],
    referrals: ['r067-lzbs'],
  },
  {
    id: 'bittorrent-2',
    icon: CoinIcons.Btt,
    name: 'BitTorrent',
    symbol: 'BTT',
    blockchains: ['TRX'],
    referrals: ['coi9-zt28'],
  },
  {
    id: 'cardano',
    icon: CoinIcons.Ada,
    name: 'Cardano',
    symbol: 'ADA',
    blockchains: ['ADA'],
    referrals: ['ddw4-8l44'],
  },
  {
    id: 'chainlink',
    icon: CoinIcons.Link,
    name: 'ChainLink',
    symbol: 'LINK',
    blockchains: ['ETH'],
    referrals: ['xpnm-ycra'],
  },
  {
    id: 'chiliz',
    icon: CoinIcons.Chz,
    name: 'Chiliz',
    symbol: 'CHZ',
    blockchains: ['ETH'],
    referrals: ['59bp-rqkz'],
  },
  {
    id: 'cosmos',
    icon: CoinIcons.Atom,
    name: 'Cosmos',
    symbol: 'ATOM',
    blockchains: ['ATOM'],
    referrals: ['3lep-weav'],
  },
  {
    id: 'crypto-com-chain',
    icon: CoinIcons.Cro,
    name: 'Crypto.com Coin',
    symbol: 'CRO',
    blockchains: ['ETH'],
    referrals: ['53v9-dbfx'],
  },
  {
    id: 'dash',
    icon: CoinIcons.Dash,
    name: 'Dash',
    symbol: 'DASH',
    blockchains: ['DASH'],
    referrals: ['yuaf-05e0'],
  },
  {
    id: 'decentraland',
    icon: CoinIcons.Mana,
    name: 'Decentraland',
    symbol: 'MANA',
    blockchains: ['ETH'],
    referrals: ['qk2z-eps4'],
  },
  {
    id: 'digibyte',
    icon: CoinIcons.Dgb,
    name: 'DigiByte',
    symbol: 'DGB',
    blockchains: ['DGB'],
    referrals: ['28b6-4rse'],
  },
  {
    id: 'dogecoin',
    icon: CoinIcons.Doge,
    name: 'Dogecoin',
    symbol: 'DOGE',
    blockchains: ['DOGE'],
    referrals: ['pdwb-af48'],
  },
  {
    id: 'dogelon-mars',
    icon: CoinIcons.Elon,
    name: 'Dogelon Mars',
    symbol: 'ELON',
    blockchains: ['ETH'],
    referrals: ['pdwb-af48'],
  },
  {
    id: 'enjincoin',
    icon: CoinIcons.Enj,
    name: 'Enjin Coin',
    symbol: 'ENJ',
    blockchains: ['ETH'],
    referrals: ['h3c2-h36r'],
  },
  {
    id: 'eos',
    icon: CoinIcons.Eos,
    name: 'EOS',
    symbol: 'EOS',
    blockchains: ['EOS'],
    referrals: ['amgj-xq2z'],
  },
  {
    id: 'ethereum',
    icon: CoinIcons.Eth,
    name: 'Ethereum',
    symbol: 'ETH',
    blockchains: ['ETH'],
    referrals: ['a83j-r7ty'],
  },
  {
    id: 'ethereum-classic',
    icon: CoinIcons.Etc,
    name: 'Ethereum Classic',
    symbol: 'ETC',
    blockchains: ['ETC'],
    referrals: ['2cia-hqii'],
  },
  {
    id: 'fantom',
    icon: CoinIcons.Ftm,
    name: 'Fantom',
    symbol: 'FTM',
    blockchains: ['FTM', 'BNB', 'ETH'],
    referrals: ['y09n-4yju'],
  },
  {
    id: 'funfair',
    icon: CoinIcons.Fun,
    name: 'FUNToken',
    symbol: 'FUN',
    blockchains: ['ETH'],
    referrals: ['7g14-zme4'],
  },
  {
    id: 'gas',
    icon: CoinIcons.Gas,
    name: 'Gas',
    symbol: 'GAS',
    blockchains: ['NEO'],
    referrals: ['FractalMedia'],
  },
  {
    id: 'holotoken',
    icon: CoinIcons.Hot,
    name: 'Holo',
    symbol: 'HOT',
    blockchains: ['ETH'],
    referrals: ['guyy-42yu'],
  },
  {
    id: 'icon',
    icon: CoinIcons.Icx,
    name: 'Icon',
    symbol: 'ICX',
    blockchains: ['ICX'],
    referrals: ['ovvz-b640'],
  },
  {
    id: 'klever',
    icon: CoinIcons.Klv,
    name: 'Klever',
    symbol: 'KLV',
    blockchains: ['TRX'],
    referrals: ['xz1q-tx7c'],
  },
  {
    id: 'kyber-network-crystal',
    icon: CoinIcons.Knc,
    name: 'KyberNetwork',
    symbol: 'KNC',
    blockchains: ['ETH'],
    referrals: ['u59r-vzx4'],
  },
  {
    id: 'lisk',
    icon: CoinIcons.Lsk,
    name: 'Lisk',
    symbol: 'LSK',
    blockchains: ['LSK'],
    referrals: ['i48c-prkz'],
  },
  {
    id: 'litecoin',
    icon: CoinIcons.Ltc,
    name: 'Litecoin',
    symbol: 'LTC',
    blockchains: ['LTC'],
    referrals: ['hrxw-a5vm'],
  },
  {
    id: 'matic-network',
    icon: CoinIcons.Matic,
    name: 'Matic (Polygon)',
    symbol: 'MATIC',
    blockchains: ['BSC', 'ETH', 'MATIC'],
    referrals: ['oewc-yhxr'],
  },
  {
    id: 'metal',
    icon: CoinIcons.Mtl,
    name: 'Metal',
    symbol: 'MTL',
    blockchains: ['ETH'],
    referrals: ['o25k-cbwg'],
  },
  {
    id: 'monero',
    icon: CoinIcons.Xmr,
    name: 'Monero',
    symbol: 'XMR',
    blockchains: ['XMR'],
    referrals: ['eudt-l3su'],
  },
  {
    id: 'nano',
    icon: CoinIcons.Nano,
    name: 'Nano',
    symbol: 'NANO',
    blockchains: ['NANO'],
    referrals: ['3ojr-om8a'],
  },
  {
    id: 'neo',
    icon: CoinIcons.Neo,
    name: 'Neo',
    symbol: 'NEO',
    blockchains: ['NEO'],
    referrals: ['6gjc-vaq3'],
  },
  {
    id: 'pancakeswap-token',
    icon: CoinIcons.Cake,
    name: 'PancakeSwap',
    symbol: 'CAKE',
    blockchains: ['BSC'],
    referrals: ['i0kx-z4kc'],
  },
  {
    id: 'qtum',
    icon: CoinIcons.Qtum,
    name: 'Qtum',
    symbol: 'QTUM',
    blockchains: ['QTUM'],
    referrals: ['4l4i-97mi'],
  },
  {
    id: 'ravencoin',
    icon: CoinIcons.Rvn,
    name: 'Ravencoin',
    symbol: 'RVN',
    blockchains: ['RVN'],
    referrals: ['91zn-yiah'],
  },
  {
    id: 'reserve-rights-token',
    icon: CoinIcons.Rsr,
    name: 'Reserve Rights',
    symbol: 'RSR',
    blockchains: ['ETH'],
    referrals: ['ifch-yect'],
  },
  {
    id: 'ripple',
    icon: CoinIcons.Xrp,
    name: 'Ripple',
    symbol: 'XRP',
    blockchains: ['XRP'],
    referrals: ['k37h-3a8l'],
  },
  {
    id: 'safemoon-2',
    icon: CoinIcons.Sfm,
    name: 'SafeMoon (V2)',
    symbol: 'SFM',
    blockchains: ['BSC'],
    referrals: ['0usu-k1nc'],
  },
  {
    id: 'saitama-inu',
    icon: CoinIcons.Saitama,
    name: 'Saitama Inu',
    symbol: 'SAITAMA',
    blockchains: ['ETH'],
    referrals: ['5qd8-bxlz'],
  },
  {
    id: 'siacoin',
    icon: CoinIcons.Sc,
    name: 'Saicoin',
    symbol: 'SC',
    blockchains: ['SC'],
    referrals: ['nyho-5wax'],
  },
  {
    id: 'shiba-inu',
    icon: CoinIcons.Shib,
    name: 'Shiba Inu',
    symbol: 'SHIB',
    blockchains: ['BSC', 'ETH', 'KCC'],
    referrals: ['e9ah-aa88'],
  },
  {
    id: 'solana',
    icon: CoinIcons.Sol,
    name: 'Solana',
    symbol: 'SOL',
    blockchains: ['BSC', 'SOL'],
    referrals: ['4f06-7nrw'],
  },
  {
    id: 'stellar',
    icon: CoinIcons.Xlm,
    name: 'Stellar Lumens',
    symbol: 'XLM',
    blockchains: ['XLM'],
    referrals: ['7gyd-0w5f'],
  },
  {
    id: 'sushi',
    icon: CoinIcons.Sushi,
    name: 'Sushi',
    symbol: 'SUSHI',
    blockchains: ['ETH'],
    referrals: ['19n2-v9sg'],
  },
  {
    id: 'tezos',
    icon: CoinIcons.Xtz,
    name: 'Tezos',
    symbol: 'XTZ',
    blockchains: ['XTZ'],
    referrals: ['6xdn-181x'],
  },
  {
    id: 'tron',
    icon: CoinIcons.Trx,
    name: 'Tron',
    symbol: 'TRX',
    blockchains: ['TRX'],
    referrals: ['o9d3-o66o'],
  },
  {
    id: 'uniswap',
    icon: CoinIcons.Uni,
    name: 'Uniswap',
    symbol: 'UNI',
    blockchains: ['ETH'],
    referrals: ['c8dz-rwtz'],
  },
  {
    id: 'tether',
    icon: CoinIcons.Usdt,
    name: 'TetherUS',
    symbol: 'USDT',
    blockchains: ['BSC', 'ETH', 'TRX'],
    referrals: ['arrh-soac'],
  },
  {
    id: 'vechain',
    icon: CoinIcons.Vet,
    name: 'VeChain',
    symbol: 'VET',
    blockchains: ['VET'],
    referrals: ['a0b3-5fbe'],
  },
  {
    id: 'waves',
    icon: CoinIcons.Waves,
    name: 'Waves',
    symbol: 'WAVES',
    blockchains: ['WAVES'],
    referrals: ['li8e-jc78'],
  },
  {
    id: 'wink',
    icon: CoinIcons.Win,
    name: 'WINk',
    symbol: 'WIN',
    blockchains: ['TRX'],
    referrals: ['cnw5-t8p2'],
  },
  {
    id: 'wrapped-bitcoin',
    icon: CoinIcons.Wbtc,
    name: 'Wrapped Bitcoin',
    symbol: 'WBTC',
    blockchains: ['ETH'],
    referrals: ['0vd5-80dq'],
  },
  {
    id: 'verge',
    icon: CoinIcons.Xvg,
    name: 'Verge',
    symbol: 'XVG',
    blockchains: ['XVG'],
    referrals: ['dbw3-04gl'],
  },
  {
    id: 'yearn-finance',
    icon: CoinIcons.Yfi,
    name: 'Yearn.finance',
    symbol: 'YFI',
    blockchains: ['ETH'],
    referrals: ['38ae-8rsz'],
  },
  {
    id: 'zcash',
    icon: CoinIcons.Zec,
    name: 'Zcash',
    symbol: 'ZEC',
    blockchains: ['ZEC'],
    referrals: ['x00k-b9ff'],
  },
  {
    id: 'zilliqa',
    icon: CoinIcons.Zil,
    name: 'Zilliqa',
    symbol: 'ZIL',
    blockchains: ['ZIL'],
    referrals: ['hcwx-r950'],
  },
];
