
name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version type (major, minor, or patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Configure Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm ci

      - name: Setup Git
        run: |
          git config user.name 'Bitcobblers'
          git config user.email 'admin@bitcobblers.com'
         
      - name: Bump Version
        run: |
          npm version --prefix releases/app ${{ github.event.inputs.version }}
          
      - name: Push Latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main --follow-tags
