name: Package Installer

on:
  push:
    branches:
      - main
      - 'releases/**'
      - ci-install-wine

jobs:
  release:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v2

      - name: Configure Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Build
        run: |
          npm run build

      - name: Perform Linting
        run: |
          npm run lint

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec tsc
          npm test

      - name: Package
        run: |
          dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          add-apt-repository ppa:cybermax-dexter/sdl2-backport
          apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          apt install --install-recommends winehq-stable
          npm run package -- --win
      
      - name: Archive Binaries
        uses: actions/upload-artifact@v3
        with:
          name: windows-installer
          path: release/build/*.exe
