name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v2

      - name: Configure Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm ci

      - name: Run Build
        run: |
          npm run build

      - name: Perform Linting
        run: |
          npm run lint

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec tsc
          npm test
