name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: self-hosted
    timeout-minutes: 10

    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v2

      - name: Configure Environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Build
        run: |
          npm run build

      - name: Perform Linting
        run: |
          npm run lint

      - name: Run Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec tsc
          npm test

      # - name: Upload Coverage Report
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: code-coverage
      #     path: coverage/lcov-report
